window.WORKSHEET_TEMPLATES = [
  {
    id: 'mind-map',
    name: '心智圖學習單',
    img: 'image_sample/worksheet-01-mind-map.svg',
    promptHint: '中心主題、放射分支、關鍵詞、延伸問題',
    desc: '適合概念發想與單元統整。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 'fishbone',
    name: '魚骨圖學習單',
    img: 'image_sample/worksheet-06-fishbone.svg',
    promptHint: '問題主軸、原因分類、證據格、結論框',
    desc: '適合分析原因、問題解決與探究討論。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 'venn',
    name: '韋恩圖學習單',
    img: 'image_sample/worksheet-11-venn.svg',
    promptHint: '重疊比較、共同點、差異點、總結句',
    desc: '適合比較兩個概念、文本或策略。',
    logicFamily: 'class',
    logicLabel: '類運算類',
  },
  {
    id: 'flowchart',
    name: '流程圖學習單',
    img: 'image_sample/worksheet-16-flowchart.svg',
    promptHint: '步驟框、箭頭、判斷點、反思題',
    desc: '適合程序、實驗步驟與因果流程。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 'timeline',
    name: '時間軸學習單',
    img: 'image_sample/worksheet-21-timeline.svg',
    promptHint: '時間節點、事件卡、因果線、回顧欄',
    desc: '適合歷史事件、故事順序與歷程整理。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 'kwl',
    name: 'KWL 表學習單',
    img: 'image_sample/worksheet-26-kwl.svg',
    promptHint: '已知、想知道、學到、下一步問題',
    desc: '適合課前啟動、課中追問與課後反思。',
    logicFamily: 'class',
    logicLabel: '類運算類',
  },
  {
    id: 'concept-map',
    name: '概念圖學習單',
    img: 'image_sample/worksheet-31-concept-map.svg',
    promptHint: '核心概念、連結詞、階層節點、例子欄',
    desc: '適合整理概念關係與知識架構。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 'decision-tree',
    name: '決策樹學習單',
    img: 'image_sample/worksheet-36-decision-tree.svg',
    promptHint: '選項分支、條件判斷、結果比較、理由欄',
    desc: '適合選擇判斷、策略比較與推理練習。',
    logicFamily: 'class',
    logicLabel: '類運算類',
  },
  {
    id: 'cycle',
    name: '循環圖學習單',
    img: 'image_sample/worksheet-41-cycle.svg',
    promptHint: '循環節點、方向箭頭、變化說明、觀察欄',
    desc: '適合自然循環、系統流程與週期概念。',
    logicFamily: 'relation',
    logicLabel: '關係運算類',
  },
  {
    id: 't-chart',
    name: 'T 字圖學習單',
    img: 'image_sample/worksheet-46-t-chart.svg',
    promptHint: '雙欄比較、證據列、判斷欄、結論句',
    desc: '適合正反比較、優缺點分析與分類整理。',
    logicFamily: 'class',
    logicLabel: '類運算類',
  },
];
